# TODO tests are not yet completed
version: 2.1
setup: true

orbs:
  cypress: cypress-io/cypress@3

jobs:
  e2e-tests:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: update apt
          command: apt-get update

      - run:
          name: install system deps
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run:
          name: Install deps
          command: "cd ./app && npm install"

      - run:
          name: Run app in background
          command: "cd ./my-app && npm run dev"
          background: true
      
      - run:
          name: Wait for app to be ready
          command: npx wait-on@latest http://localhost:3000

      - cypress/run-tests:
          cypress-command: "npx cypress run"
          working-directory: ./my-app

      - store_artifacts:
          path: ./my-app/cypress/screenshots
          when: on_fail

workflows:
  the-great-gatsby:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only:
                - main2.0
